# fly.toml app configuration file generated for fullstackopen2024part3-small-shape-4743 on 2024-01-16T18:02:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackopen2024part3-small-shape-4743"
primary_region = "arn"

[build]

[env]
  PORT = "3000"

[processes]
  app = 'node index.js'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  strategy = "canary"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
